name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *' # every 30 minutes

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: nentenpizza
          base: master
          head: master