name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *' # каждые 15 минут
  workflow_dispatch: # можно вручную запустить

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync upstream changes
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: nentenpizza
          base: master
          head: master
          token: ${{ secrets.TOKEN }}
